# Generated by Django 5.0.6 on 2024-05-22 02:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=1000)),
                ('expenses_folder_id', models.CharField(max_length=500)),
                ('owner_folder_id', models.CharField(max_length=500)),
                ('property_folder_id', models.CharField(max_length=500)),
                ('onboarding_start_date', models.DateField()),
                ('launch_date', models.DateField()),
            ],
        ),
    ]
