# Generated by Django 5.0.6 on 2024-05-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingobject',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingobject',
            name='expenses_folder_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingobject',
            name='launch_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingobject',
            name='onboarding_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingobject',
            name='owner',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingobject',
            name='owner_folder_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingobject',
            name='property_folder_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
